name: 'Build snapshot release'
on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'
            - name: Build with Maven
              run: mvn --batch-mode --update-snapshots package
            - name: Run Aqua scanner
              uses: docker://aquasec/aqua-scanner
              with:
                  args: trivy fs --scanners config,vuln,secret --sast .
                  # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
                  # To enable SAST scanning, add: --sast
                  # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
              env:
                  AQUA_KEY: ${{ secrets.AQUA_KEY }}
                  AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
                  GITHUB_TOKEN: ${{ github.token }}
                  AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
                  CSPM_URL: https://eu-1.api.cloudsploit.com
                  TRIVY_RUN_AS_PLUGIN: 'aqua'
                  # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)
